version: '3'
services:
  database:
    build:
      context: .
      dockerfile: dockerfile_db
    environment:
      - POSTGRES_PASSWORD=student
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d info21_db -p 5432 -U student"]
    restart: unless-stopped
    container_name: info21_db
    tty: true
  application:
    build:
      context: .
      dockerfile: dockerfile_app
    volumes:
      - ./info21_web:/code/info21_web
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    container_name: info21_app
    tty: true
